---
title: "clean_CA"
output: github_document
author: Jason Gao
date: "2025-11-05"
---
# ---- upload packages ----
```{r upload packages}
library(tidyverse)
library(janitor)
library(stringr)
library(readr)
library(dplyr)
raw_data<-read.csv("datasets/ca_dental.csv")
head(raw_data)
```
# ---- clean datasets ----
```{r}
clean_data <- raw_data %>%
  # 1️⃣ 清理 Measure 括号
  mutate(Measure = str_trim(str_remove_all(Measure, "\\s*\\([^\\)]+\\)"))) %>%
  
  # 2️⃣ 创建三类
  mutate(service_group_3 = case_when(
    str_detect(Measure, regex("Preventive|Sealant", ignore_case = TRUE)) ~ "Preventive care",
    str_detect(Measure, regex("Restorative|Caries|Treatment", ignore_case = TRUE)) ~ "Treatment care",
    str_detect(Measure, regex("Annual Dental Visit|Exam|Evaluation|Diagnostic", ignore_case = TRUE)) ~ "Dental access",
    TRUE ~ "Other"
  )) %>%
  
  # 3️⃣ 删除 "No data available" 等无效描述
  mutate(desc_clean = str_to_lower(str_squish(`Users.Annotation.Description`))) %>%
  filter(
    is.na(desc_clean) |
      !desc_clean %in% c(
        "no data available",
        "cell suppressed for small numbers",
        "cell suppressed for complementary cell"
      )
  ) %>%
  
  # 4️⃣ 删除所有 Annotation 类列
  select(
    -starts_with("Users.Annotation"),
    -starts_with("Denominator.Annotation"),
    -starts_with("Utilization.Annotation"),
    -starts_with("service_group_3"),
    -desc_clean
  ) |>
  janitor::clean_names() |>
  rename(
    year = calendar_year,
    measure = measure,
    age_group = age_filter,
    users = users,
    denom_3m = denominator_3_months_continuous_eligibility,
    )
 
# 查看清理后结果
head(clean_data)
```
# ---- save as new document ----
```{r}
write_csv(clean_data, "datasets/clean_ca.csv")
```

